spring.application.name=mi-primer-api-rest

server.port=8092

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=jdbc:mysql://localhost:3306/db_springboot_dev?useSSL=false


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect